# Generated by Django 3.1.1 on 2020-10-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200927_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
