# Generated by Django 3.1.1 on 2020-10-04 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='index',
        ),
        migrations.AddField(
            model_name='spider',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
